algoritmo "EX 3"

var
   n1, n2, n3, quaN1, quaN2,quaN3, sq, qd: inteiro
inicio
   Escreva("Digite o primeiro valor: ")
   Leia(n1)
   Escreva("Digite o segundo valor: ")
   Leia(n2)
   Escreva("Digite o terceiro valor: ")
   Leia(n3)
   quaN1 <- n1*n1
   quaN2 <- n2*n2
   quaN3 <- n3*n3
   sq <- quaN1+quaN2+quaN3
   qd <- (n1+n2+n3)*(n1+n2+n3)
   Escreval("A soma dos três valores ao quadrado é ", sq)
   Escreva("O quadrado da soma é ", qd)
   

   
fimalgoritmo
