algoritmo "Estados por Região"

var
regiao: inteiro
inicio
Escreval("Escolha a região: ")
Escreva("1 - NORTE / 2 - SUL / 3 - NORDESTE / 4 - SUDESTE / 5 - CENTRO-OESTE : ")
Leia(regiao)
LIMPATELA

Escolha(regiao)
Caso 1
   Escreval("Estados da região Norte: ")
Caso 2
     Escreval("Estados da região Sul: ")
Caso 3
     Escreval("Estados da região Nordeste: ")
Caso 4
     Escreval("Estados da região Sudeste: ")
Caso 5
     Escreval("Estados da região Centro-Oeste ")


OutroCaso
         Escreval("Valor inválido")
FimEscolha

fimalgoritmo
