algoritmo "Exercicio 5"

var
nome, sexo, signo, materia_predileta, tipo_sanguineo: caractere
trabalha_na_area, cidade, estado, logradouro, endereco: caractere
idade, ra: inteiro
altura, peso: real
inicio

escreva("Digite o seu nome: ")
leia(nome)
escreva("Digite a sua idade: ")
leia(idade)
escreva("Digite o seu sexo: ")
leia(sexo)
escreva("Digite a sua altura: ")
leia(altura)
escreva("Digite o seu peso: ")
leia(peso)
escreva("Digite o seu ra: ")
leia(ra)
escreva("Digite o seu signo: ")
leia(signo)
escreva("Digite sua matéria predileta: ")
leia(materia_predileta)
escreva("Digite o seu tipo sanguíneo: ")
leia(tipo_sanguineo)
escreva("Digite em que área você trabalha: ")
leia(trabalha_na_area)
escreva("Digite a cidade em que você vive: ")
leia(cidade)
escreva("Digite o estado em que você vive: ")
leia(estado)
escreva("Digite o logradouro em que você mora: ")
leia(logradouro)
escreva("Digite o endereço em que você mora: ")
leia(endereco)
escreval("__________________________________")
escreval("********* Dados cadastrais  *********")
escreval("")
escreval("Nome: ", nome)
escreval("Idade: ", idade)
escreval("Sexo: ", sexo)
escreval("Altura: ", altura)
escreval("Peso: ", peso)
escreval("RA: ", ra)
escreval("Signo: ", signo)
escreval("Matéria predileta: ", materia_predileta)
escreval("Tipo sanguíneo: ", tipo_sanguineo)
escreval("Trabalha na área: ", trabalha_na_area)
escreval("Cidade: ", cidade)
escreval("Estado: ", estado)
escreval("Logradouro: ", logradouro)
escreval("Endereço: ", endereco)

fimalgoritmo
