algoritmo "Dia da Semana"

var
n1: inteiro
inicio
Escreva("Digíte um valor entre 1 e 7: ")
Leia(n1)
Se(n1 = 1) entao
   Escreva("Domingo")
Senao
   Se (n1 =2) entao
      Escreva("Segunda-Feira")
   Senao
      Se(n1 = 3) entao
         Escreva("Terça-Feira")
      Senao
         Se (n1 = 4) entao
            Escreva("Quarta-Feira")
         Senao
            Se(n1 = 5) entao
               Escreva("Quinta-Feira")
            Senao
               Se (n1 = 6) entao
                  Escreva("Sexta-Feira")
               Senao
                  Se (n1 = 7) entao
                     Escreva("Sábado")
                  Senao
                       ("NÚMERO INVÁLIDO")
                  FimSe
               FimSe
            FimSe
         FimSe
      FimSe
   FimSe
FimSe


fimalgoritmo
