algoritmo "Ex 6"
var
   a, b, c, aTrap, aQua : real
inicio
      Escreva("Digíte o valor da base maior: ")
      Leia(a)
      Escreva("Digíte o valor da base menor: ")
      Leia(b)
      Escreva("Digíte o valor da altura: ")
      Leia(c)
      aTrap <- (a + b)*c^2
      aQua <- b^2
      Escreval("A área do trapézio é ", aTrap)
      Escreva("A área do quadrado é ", aQua)
      
      
fimalgoritmo
