algoritmo "Ex 7"

var
   nome: caracter
   horas, valHora, sal,  salFilho1, salFilho2: real
   filhos: inteiro
inicio
      Escreva("Qual o nome do funcionário? ")
      Leia(nome)
      Escreva("Quantas horas ele trabalha? ")
      Leia(horas)
      Escreva("Quanto ele ganha por hora? ")
      Leia(valHora)
      sal <- valHora*horas
      Escreva("Quantos filhos ele tem? ")
      Leia(filhos)
      Escreva
      
      
fimalgoritmo
